PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I am LORELEI of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "But defensively this type is ass.\n"
    .string "Like, so ass.\p"
    .string "Hahaha!\n"
    .string "If you lose to me you're trash.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I, LORELEI of the ELITE FOUR,\n"
    .string "have returned!\p"
    .string "You know how it goes.\n"
    .string "No one can best me when it comes\l"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your POKéMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Yeah. You beat an ice type\n"
    .string "trainer big deal asshat.$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Why are you still here.\n"
    .string "Leave dude.$"

