CeladonCity_Gym_Text_ErikaIntro::
    .string "Hello…\n"
    .string "Lovely weather, isn't it?\l"
    .string "It's so pleasant…\p"
    .string "…Oh, dear…\n"
    .string "…Oh, Gosh…\p"
    .string "…Oh, Golly…\n"
    .string "…Oh, Me…\p"
    .string "…Oh, My…\n"
    .string "…Howdy dooty…\p"
    .string "…Rootin tootin…\n"
    .string "…Grass type…\p"
    .string "…Oh, I'm sorry, I had no idea that\n"
    .string "you wished to challenge me.\p"
    .string "You better Shou up then.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh!\n"
    .string "I concede defeat.\l"
    .string "You play so boring.\p"
    .string "I simply don't care\n"
    .string "enough.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "You are cataloging POKéMON?\n"
    .string "I must say I'm impressed.\p"
    .string "I would never collect POKéMON if\n"
    .string "they were unattractive.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "The RAINBOWBADGE will make\n"
    .string "POKéMON up to Lv. 50 obey.\p"
    .string "It also allows POKéMON to use\n"
    .string "STRENGTH in and out of battle.\p"
    .string "Please also take this with you.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "Paul received TM19\n"
    .string "from ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 contains GIGA DRAIN.\p"
    .string "Call me if you ever need\n"
    .string "a GIGA DRAIN.\p"
    .string "WINK$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro::
    .string "I should tell you about this GYM.\p"
    .string "Only real ladies are allowed in\n"
    .string "here!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "You're too rough!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Bleaah!\n"
    .string "I hope ERIKA wipes you out!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Oh, welcome.\n"
    .string "I was getting bored.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Fuck off dude.$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "GRASS-type POKéMON are tough\n"
    .string "against the WATER type.\p"
    .string "They also have an edge on ROCK-\n"
    .string "and GROUND-type POKéMON.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Weren't you peeking in here\n"
    .string "earlier?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Locked in.$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Oh, you were looking at ERIKA…\n"
    .string "You weren't looking at me…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Look, look!\n"
    .string "See my POKéMON!\p"
    .string "I like the GRASS type.\n"
    .string "I like Chikorita.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "We only use GRASS-type POKéMON at\n"
    .string "our GYM.\p"
    .string "Why? We also use them for making\n"
    .string "flower arrangements!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Oh, hey!\p"
    .string "We don't like Fairy- or FIRE-type\n"
    .string "POKéMON in here!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Lego Yoda death noise$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Our LEADER ERIKA might be quiet,\n"
    .string "but she's famous around here.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Pleased to meet you.\n"
    .string "My hobby is PAULKéMON training.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "Splendid!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "I have a blind date coming up.\n"
    .string "I have to learn to be polite,\l"
    .string "especially if I have to battle.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Welcome to CELADON GYM!\p"
    .string "You'd better not underestimate\n"
    .string "the nice ladies here.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Oh!\n"
    .string "Beaten!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "I didn't bring my best POKéMON.\n"
    .string "Wait until next time!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

