CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "Only those TRAINERS who have a\n"
    .string "policy about POKéMON can turn pro.\p"
    .string "If you want to go pro in a game\n"
    .string "just play pyro in tf2!\p"
    .string "Pyro is the easiest class\n"
    .string "by far!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an fish-type POKéMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The CASCADEBADGE makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "Imagine if Pokemon always\n"
    .string "obeyed you...\p"
    .string "I'd catch a Cinderace and\n"
    .string "then go crazy town on him.\p"
    .string "You can CUT down small trees to\n"
    .string "open new pathways.\p"
    .string "You, have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "Paul received TM03\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "You're too much!\p"
    .string "All right!\p"
    .string "You can have the CASCADEBADGE to\n"
    .string "show you beat me.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "What? You?\n"
    .string "I'm more than gooder than you!\p"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "Bitchass coward!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses FISH-type POKéMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type POKéMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "POKéMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, Paul$"

