PokemonLeague_ChampionsRoom_Text_Intro::
    .string "Roman: Hey, Paul!\p"
    .string "I was looking forward to seeing\n"
    .string "you, Paul.\p"
    .string "I made this for you\n"
    .string "Paul.\p"
    .string "Paul,\n"
    .string "Paul Paul Paul.\p"
    .string "Not only that, Paul.\p"
    .string "And now…\p"
    .string "I'm the Paul!\p"
    .string "Paul!\n"
    .string "Do you know what that means?\p"
    .string "I'll tell you.\p"
    .string "You're about to be unpauled.$"

PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .string "Roman: Hey, Paul!\p"
    .string "You came back, Paul!\n"
    .string "Hahah, that is so great!\p"
    .string "My rival should be strong to keep\n"
    .string "me sharp.\p"
    .string "While working on my POKéDEX, I\n"
    .string "looked all over for POKéMON.\p"
    .string "Not only that, I assembled teams\n"
    .string "that would beat any POKéMON type.\p"
    .string "And now…\p"
    .string "I'm the POKéMON LEAGUE CHAMPION!\p"
    .string "Paul!\n"
    .string "Do you know what that means?\p"
    .string "I'll tell you.\p"
    .string "I am the most powerful TRAINER in\n"
    .string "the world!$"

PokemonLeague_ChampionsRoom_Text_Defeat::
    .string "You are...\n"
    .string "THE TRUE PAUL!$"

PokemonLeague_ChampionsRoom_Text_Victory::
    .string "はーはッ！\n"
    .string "かった！　かった！　かった！\p"
    .string "Paulに　まける　ような\n"
    .string "おれさま　では　なーい！\p"
    .string "ま！　ポケモンの\n"
    .string "てんさい　{RIVAL}さま　あいてに\l"
    .string "ここまで　よく　がんばった！\p"
    .string "ほめて　つかわす！\n"
    .string "はーッ！　はーはッはッ！$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
    .string "Why?\n"
    .string "Why did I lose?\p"
    .string "I never made any mistakes raising\n"
    .string "my POKéMON…\p"
    .string "Fuck you man.$"

PokemonLeague_ChampionsRoom_Text_OakPlayer::
    .string "OAK: Paul!$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
    .string "OAK: Paul!$"

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
    .string "OAK: {RIVAL}…\n"
    .string "You are certainly no Paul.$"

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
    .string "OAK: Paul.\p"
    .string "Paul!\n"
    .string "Paul Paul Paul Paul!$"

