SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "Paul: Hi!\n"
    .string "Do you like POKéMON?\p"
    .string "Paul: Uh, no, I just asked you.\p"
    .string "Paul: Huh?\n"
    .string "You're strange!\p"
    .string "COPYCAT: Hmm? Quit mimicking?\n"
    .string "But, that's my favorite hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "Paul: Hi.\n"
    .string "You must like POKéMON.\p"
    .string "Paul: No, not me.\n"
    .string "I asked you.\p"
    .string "Paul: Pardon?\n"
    .string "You're weird!\l"
    .string " \l"
    .string "COPYCAT: Hmm? Quit mimicking?\l"
    .string "But that's my favorite hobby!$"

Text_MimicTeach::
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"

Text_MimicDeclined::
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale::
    .string "Paul: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "Paul: Pardon?\p"
    .string "Paul: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale::
    .string "Paul: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "Paul: Pardon?\p"
    .string "Paul: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "Paul“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "Paul“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "Paul“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "Paul“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "Paul“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "Paul“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME,\n"
    .string "SEE HOW PRETTY I CAN BE?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "This is a rare POKéMON!\n"
    .string "Huh? It's only a doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "A game with MARIO wearing a bucket\n"
    .string "on his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite POKéMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
