PokemonLeague_AgathasRoom_Text_Intro::
	.string "Welcome, my name is GLACIA\n"
	.string "of the ELITE FOUR.\p"
	.string "I've traveled from afar to HOENN\n"
	.string "so that I may hone my nice skills.\p"
	.string "But all I have seen are challenges by\n"
	.string "weak TRAINERS and their POKéMON.\p"
	.string "What about you?\p"
	.string "It would please me to no end if I could\n"
	.string "go all out against you!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "You're the child that OAK's taken\n"
    .string "under his wing, aren't you?\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "Paul! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Ngl!\n"
    .string "I stole that from someone!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "That did not work.$"

